import { Component } from '@angular/core';
import { NavController } from 'ionic-angular';
import {
  Push,
  PushToken
} from '@ionic/cloud-angular';
import { Http, Headers } from '@angular/http';

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {
 	
  constructor(public navCtrl: NavController, public push: Push, public http: Http) {
  	//below code will throw an error if not running on a device
  	this.push.register().then((t: PushToken) => {
	  return this.push.saveToken(t, {ignore_user: true});
	}).then((t: PushToken) => {
		console.log(t.token);
	  let headers = new Headers();
	  headers.append("Content-Type","application/json");
	  let body = {
	  	token: t.token
	  };
	  //post device token to server, server url coming from secure tunnel to localhost generated by ngRok plugin
	  this.http.post("https://51905e24.ngrok.io/token", JSON.stringify(body), {headers: headers})
	  .map(res => res.json())
	  .subscribe(data => {
	  	console.log(data);
	  });
	});
	this.push.rx.notification()
	  .subscribe((msg) => {
	    alert(/*msg.title + ': ' + */ msg.text);
	  });

}

}
